### ISSUE TITLE
Build:markdown unsuccessful using 'yarn start'

### ISSUE THREAD

**Issue by simonpeterdebbarma** [tyroprogrammer/learn-react-app#25]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\simon\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:markdown' ]
2 info using npm@6.1.0
3 info using node@v6.11.4
4 verbose run-script [ 'prebuild:markdown', 'build:markdown', 'postbuild:markdown' ]
5 info lifecycle learn-react-app@0.1.0~prebuild:markdown: learn-react-app@0.1.0
6 info lifecycle learn-react-app@0.1.0~build:markdown: learn-react-app@0.1.0
7 verbose lifecycle learn-react-app@0.1.0~build:markdown: unsafe-perm in lifecycle true
8 verbose lifecycle learn-react-app@0.1.0~build:markdown: PATH: C:\Users\simon\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\simon\Repos\learn-react-app\node_modules\.bin;C:\Users\simon\Repos\learn-react-app\node_modules\.bin;C:\Users\simon\AppData\Local\Yarn\Data\link\node_modules\.bin;C:\Users\simon\Repos\learn-react-app\node_modules\.bin;C:\Users\simon\AppData\Local\Yarn\Data\link\node_modules\.bin;C:\Program Files\libexec\lib\node_modules\npm\bin\node-gyp-bin;C:\Program Files\lib\node_modules\npm\bin\node-gyp-bin;C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Program Files\nodejs;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Java\jdk1.8.0_172\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Gradle\gradle-4.7\bin;C:\Program Files (x86)\Yarn\bin\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Users\simon\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\simon\AppData\Roaming\npm;C:\Users\simon\AppData\Local\Yarn\bin;C:\Program Files\heroku\bin;C:\src\flutter_windows_v1.0.0-stable\flutter\bin;
9 verbose lifecycle learn-react-app@0.1.0~build:markdown: CWD: C:\Users\simon\Repos\learn-react-app
10 silly lifecycle learn-react-app@0.1.0~build:markdown: Args: [ '/d /s /c', 'node scripts/processMarkdown' ]
11 silly lifecycle learn-react-app@0.1.0~build:markdown: Returned: code: 1  signal: null
12 info lifecycle learn-react-app@0.1.0~build:markdown: Failed to exec build:markdown script
13 verbose stack Error: learn-react-app@0.1.0 build:markdown: `node scripts/processMarkdown`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\simon\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\simon\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:920:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
14 verbose pkgid learn-react-app@0.1.0
15 verbose cwd C:\Users\simon\Repos\learn-react-app
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\simon\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:markdown"
18 verbose node v6.11.4
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error learn-react-app@0.1.0 build:markdown: `node scripts/processMarkdown`
22 error Exit status 1
23 error Failed at the learn-react-app@0.1.0 build:markdown script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by tyroprogrammer** [comment]
@simonpeterdebbarma this could be because of node version - I will look into this in detail. In the meantime you can probably try upgrading your node. I have node - 10.4.2 and npm - 6.4.1 locally.

**Comment by wildeink** [comment]
Having the same issue even with an up-to-date node & npm. 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.4.1
3 info using node@v10.15.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle learn-react-app@0.1.0~prestart: learn-react-app@0.1.0
6 info lifecycle learn-react-app@0.1.0~start: learn-react-app@0.1.0
7 verbose lifecycle learn-react-app@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle learn-react-app@0.1.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/chrisjoy/Code/learn-react-app/learn-react-app/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Users/chrisjoy/lib/vsts-cli/bin:/Users/chrisjoy/lib/vsts-cli/bin
9 verbose lifecycle learn-react-app@0.1.0~start: CWD: /Users/chrisjoy/Code/learn-react-app/learn-react-app
10 silly lifecycle learn-react-app@0.1.0~start: Args: [ '-c', 'npm run build:markdown && react-scripts start' ]
11 silly lifecycle learn-react-app@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle learn-react-app@0.1.0~start: Failed to exec start script
13 verbose stack Error: learn-react-app@0.1.0 start: `npm run build:markdown && react-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid learn-react-app@0.1.0
15 verbose cwd /Users/chrisjoy/Code/learn-react-app/learn-react-app
16 verbose Darwin 18.2.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v10.15.1
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error learn-react-app@0.1.0 start: `npm run build:markdown && react-scripts start`
22 error Exit status 1
23 error Failed at the learn-react-app@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by simonpeterdebbarma** [comment]
@tyroprogrammer The issue persists with an up-to-date node and npm.

**Comment by tyroprogrammer** [comment]
@simonpeterdebbarma, @wildeink - have you tried deleting `node_modules` and installing it again? In the root directory:
```
rm -rf node_modules
npm cache clean
npm install
```

**Comment by wildeink** [comment]
An updated version of eslint seems to be causing the failed build (for me). Adding SKIP_PREFLIGHT_CHECK=true to my .env file in the root allowed the app to build/start with npm and yarn.

**Comment by tyroprogrammer** [comment]
Hope what @wildeink suggested worked! Closing this issue for now.
