### ISSUE TITLE
Potential improvement: 

### ISSUE THREAD

**Issue by davebneufeld** [tyroprogrammer/learn-react-app#36]
In Section: Handling Events
    http://localhost:3000/tutorial/handling-events

The first example creates a function that contains a button 
   "function ClickableButton(props){ ..."
The second example creates a function that contains an InputBox
   but it still uses the name ClickableButton

Although this is not an error, using the second function name confused me since I thought the two examples were talking about the same thing until I cut and pasted them to do a quick comparison. 
recommended solution: Changing the second name to function "ChangeableInput" would reduce the confusion. 
---------

BTW: excellent tutorial. thank you.

**Comment by tyroprogrammer** [comment]
@davebneufeld - Thanks for pointing this out!
